#!/bin/bash

#PBS -N GAMER
#PBS -M PUT_YOUR_EMAIL_HERE
#PBS -m abe
#PBS -q workq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=16:ppn=6
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID

cd $PBS_O_WORKDIR

##************************************************
##*** remember to set "OPT__GPUID_SELECT = -2" ***
##************************************************

## for openmpi-1.6.0
##mpirun -np 32 -npernode 2 ./gamer 1>>log 2>&1

## for openmpi-1.4.3-qlc
mpirun -np 32 -npernode 2 -hostfile $PBS_NODEFILE -bind-to-socket ./gamer 1>>log 2>&1

## for openmpi-3.1.4
mpirun -map-by ppr:2:socket:pe=8 ./gamer 1>>log 2>&1

## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr
