#!/bin/sh
#PBS -N GAMER.1.0.beta5.3.0
#PBS -r n
#PBS -q n4
#PBS -l nodes=4:ppn=3
##PBS -W depend=afterok:JOB_ID

export P4_GLOBMEMSIZE=2000187896

cd $PBS_O_WORKDIR

NPROCS=`wc -l < $PBS_NODEFILE`

echo "Starting on `hostname` at `date`"

#mpirun --mca btl ^tcp -hostfile $PBS_NODEFILE -np $NPROCS ./Dizzy 1>stdout 2>stderr
time mpiexec -np $NPROCS ./Dizzy 1>stdout 2>stderr

echo "Job Ended at `date`"

