###############################################
#         GNU MPI job script example          #
###############################################

#!/bin/bash

#SBATCH --account=ACCOUNT                                   # (-A) Account/project number
#SBATCH --job-name=JOB_NAME                                 # (-J) Job name
#SBATCH --partition=ctest                                   # (-p) Specific slurm partition
#SBATCH --ntasks=8                                          # (-n) Number of total MPI tasks (i.e. processes)
#SBATCH --nodes=2                                           # (-N) Maximum number of nodes to be allocated
#SBATCH --ntasks-per-node=4                                 # Maximum number of tasks on each node
#SBATCH --cpus-per-task=14                                  # (-c) Number of cores per MPI task
#SBATCH --mem=65536                                         # Memory limit per compute node for the  job.Do not use with mem-per-cpu flag
#SBATCH --time=00:30:00                                     # (-t) Wall time limit (days-hrs:min:sec)
##SBATCH -o log_taiwania_III
##SBATCH -e job.%j.err
##SBATCH --mail-type=BEGIN,END,FAIL                         # Mail events (NONE, BEGIN, END, FAIL, ALL)
##SBATCH --mail-user=EMAIL_ADDRESS                          # Where to send mail.  Set this to your email address

LOG_FILE=log_taiwania_III_gnu_4.8.5

module purge
module load compiler/gcc/4.8.5 OpenMPI/4.1.0
module list >> $LOG_FILE

export LD_LIBRARY_PATH="/opt/ohpc/Taiwania3/libs/gcc485/ompi410/hdf5-1.12/lib:FFTW_PATH/lib:$LD_LIBRARY_PATH"

mpirun -map-by ppr:2:socket:pe=14 --report-bindings ./gamer 1>>$LOG_FILE 2>&1
echo "=============================================================" >> $LOG_FILE
