#!/bin/bash

#PBS -N gamer
#PBS -M PUT_YOUR_EMAIL_HERE
#PBS -m abe
#PBS -q workq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=1:ppn=32
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

if [ "$PBS_ENVIRONMENT" == "PBS_BATCH" ]; then
   cd $PBS_O_WORKDIR
fi

LOG_FILE=log

module purge 1>>$LOG_FILE 2>&1
module load intel/oneapi-2023.1.0 fftw/3.3.10-intel-2023.1.0-openmpi-4.1.5-ucx_mt openmpi/4.1.5-ucx_mt-intel-2023.1.0 \
            hdf5/1.10.6-intel-2023.1.0 gsl/2.6-intel-2023.1.0 cuda/12.1 valgrind/3.15.0 1>>$LOG_FILE 2>&1
module list 1>>$LOG_FILE 2>&1


mpirun -map-by ppr:4:socket:pe=8 --report-bindings ./gamer 1>>$LOG_FILE 2>&1


## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>$LOG_FILE 2>&1

echo "Terminating CUDA MPS server" >> $LOG_FILE
mpirun -map-by ppr:1:node:pe=1 kill_nvidia_MPS_local.sh 1>>$LOG_FILE 2>&1
