#!/bin/bash
#PBS -N ExtractProfile
#PBS -M hyschive@gmail.com
#PBS -m abe
#PBS -k n
##PBS -q workq
##PBS -q secondary
#PBS -q ncsa
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=6
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

cd $PBS_O_WORKDIR

FILE_IN=??
START_ID=??
END_ID=??
DELTA_ID=1

source MultiFiles__GAMER_ExtractProfile.sh $FILE_IN $START_ID $END_ID $DELTA_ID 1>stdout 2>stderr
