#!/bin/bash

#PBS -N profile
#PBS -M hyschive@phys.ntu.edu.tw
#PBS -m abe
#PBS -q workq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=1:ppn=16
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

if [ "$PBS_ENVIRONMENT" == "PBS_BATCH" ]; then
   cd $PBS_O_WORKDIR
fi

FILE_IN=??
START_ID=??
END_ID=??
DELTA_ID=1

source MultiFiles__GAMER_ExtractProfile.sh $FILE_IN $START_ID $END_ID $DELTA_ID 1>stdout 2>stderr
