#!/bin/bash

#PBS -N gamer_isolatedhalo_test_yt
##PBS -M d07222009@ntu.edu.tw
##PBS -m abe
#PBS -q gtx1080tiq
#PBS -k n
#PBS -l walltime=72:00:00:00
#PBS -l nodes=1:ppn=16
##nodes = use how many computers, one computer has only 128G
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:33611

export OMP_NUM_THREADS=1

LOG_FILE=log_gamer_libyt
EXE=gamer

if [ "$PBS_ENVIRONMENT" != "PBS_INTERACTIVE" ]; then
   cd $PBS_O_WORKDIR
fi

export OMPI_MCA_osc=sm,pt2pt
mpirun -map-by ppr:4:socket:pe=4 --report-bindings --output-filename $LOG_FILE ./$EXE  #for AMR, pe means how many threads you want to fork out
