name: 🐟 Assign Task
description: Assign a new set of tasks (Dev Team Only)

body:

  - type: markdown
    attributes:
      value: |
        🐟🐟🐟🐟🐟🐟🐟🐟🐟|| DEV TEAM ONLY ||🐟🐟🐟🐟🐟🐟🐟🐟🐟
        This is a template for the development team to assign a new set of tasks.
        If you are not a member of the team, please do not use this template.
        🐟🐟🐟🐟🐟🐟🐟🐟🐟|| DEV TEAM ONLY ||🐟🐟🐟🐟🐟🐟🐟🐟🐟

  - type: textarea
    id: goal
    attributes:
      label: 🎯 Goals
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: 📋 Mandatory tasks
      value: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true

  - type: textarea
    id: opt_task
    attributes:
      label: Optional tasks
      value: |
        - [ ] Task A
        - [ ] Task B
  
  - type: textarea
    id: additional
    attributes:
      label: References

  - type: textarea
    id: note
    attributes:
      label: Supplementary info
