#!/bin/bash

NAME=$1


if [ -z "$NAME" ];then
   echo "error: Please provide source code"
   exit
fi


OUT=${NAME%.cpp}

EOS=APPROXIMATED_GENERAL
#EOS=CONSTANT_GAMMA
CONSERVED_ENERGY=2
PRECISION=FLOAT8


g++ $1  CPU_Shared_FluUtility.cpp \
-DCONSERVED_ENERGY=$CONSERVED_ENERGY \
-DSERIAL \
-DLR_SCHEME=PLM \
-DMODEL=SR_HYDRO \
-DRANDOM_NUMBER=RNG_GNU_EXT \
-DFLU_SCHEME=MHM \
-DRSOLVER=HLLC \
-DNLEVEL=10 \
-DMAX_PATCH=200000 \
-D$PRECISION \
-DEOS=$EOS -lm -o $OUT && ./$OUT
