#!/bin/bash

NAME=$1
OUT=${NAME%.cpp}

g++ $1  CPU_Shared_FluUtility.cpp \
-DCONSERVED_ENERGY=2 \
-DSERIAL \
-DLR_SCHEME=PLM \
-DMODEL=SR_HYDRO \
-DRANDOM_NUMBER=RNG_GNU_EXT \
-DFLU_SCHEME=MHM \
-DRSOLVER=HLLC \
-DNLEVEL=10 \
-DMAX_PATCH=200000 \
-DFLOAT8 \
-DEOS=APPROXIMATED_GENERAL \
-lm -o $OUT && ./$OUT
#-DEOS=APPROXIMATED_GENERAL
#-DEOS=CONSTANT_GAMMA      
