#!/bin/bash

#PBS -N gamer
#PBS -M colonist288@gmail.com
#PBS -m abe
#PBS -q workq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=2:ppn=16
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

# array is the indices of data files
# R is BOX_SIZE/2

array=(01 02 03)
R=1.5

if [ "$PBS_ENVIRONMENT" != "PBS_INTERACTIVE" ]; then
   cd $PBS_O_WORKDIR
fi

cp ../Data_000000 Data_i
./GAMER_ExtractProfile  -D -i Data_i -S -r 0.5 -n 128 -x $R -y $R -z $R -p 1>>log 2>&1
mv AveParDens AveParDens_init

for i in "${array[@]}"
do
   cp ../"Data_0000"$i Data_f
   ./GAMER_ExtractProfile  -D -i Data_f -S -r 0.5 -n 128 -x $R -y $R -z $R -p
   mv AveParDens AveParDens_final
   gnuplot plot_profile.gpt
        mv Density_Profile.png Halo_1M_0_$i.png
done


## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr

