Compilation flags:
========================================
Enable  : MODEL=HYDRO, GRAVITY, PARTICLE, MHD (optional),
          SUPPORT_HDF5, NPAR_ATT_USER=0,
          NCOMP_PASSIVE_USER >= Merger_Coll_NumHalos + Merger_Coll_UseMetals
          (these are parameters in Input__TestProb)
Disable : COMOVING


Default setup:
========================================
1. Units:
   (1) External (for Input__TestProb only):
       [L] = kpc
       [V] = km/s

   (2) Internal (for all other input files and internal usage):
       [L] = Mpc
       [M] = 1.0e14 Msun
       [T] = 1.0e1 Gyr
    -->[V] = [L]/[T] ~ 9.8e1 km/s
    -->[D] = [M]/[L]^3 ~ 6.8e-27 g/cm^3

2. Default resolution ~ 15 kpc (MAX_LEVEL = 3)


Note:
========================================
1. Mimic the merging cluster simulation setup of Flash provided by John ZuHone
   --> John ZuHone, 2011, ApJ, 728, 54 (arXiv:1004.3820), but the initial conditions
       are somewhat different
2. Run the script "download_ic.sh" to download the initial condition files for this test
   --> These files are generated by John ZuHone
3. Alternatively, you can construct the ICs yourself using the "cluster_generator" package
   WARNING: This package is under development and currently has poor documentation, contact
   jzuhone@gmail.com for details
   --> Install cluster_generator from GitHub and run the included gamer_cluster_ics.py script
       (1) git clone https://github.com/jzuhone/cluster_generator (somewhere else probably)
       (2) cd cluster_generator
       (3) [Optional] Update SciPy to version >= 1.13.0
       (4) python -m pip install .
       (5) Go back to the gamer_cluster_ics.py script and run with "python gamer_cluster_ics.py"
4. No need to set PAR_NPAR in Input__Parameter since it will be reset automatically.
5. Some handy yt analysis scripts and a notebook are put in "yt_script"
   --> For example, to generate the slice plots, one can
       (1) cd yt_script
       (2) Edit "idx_start" and "idx_end" in plot_slice-z.py
       (3) python plot_slice-z.py (or mpirun -np NUMBER_OF_CPU_CORES_YOU_HAVE python plot_slice-z.py)
