#!/bin/bash

#PBS -N gamer
#PBS -M PUT_YOUR_EMAIL_HERE
#PBS -m abe
#PBS -q allq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=6:ppn=16
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID

if [ "$PBS_ENVIRONMENT" == "PBS_BATCH" ]; then
   cd $PBS_O_WORKDIR
fi

mpirun -map-by ppr:16:socket:pe=1 --report-bindings ./gamer 1>>log 2>&1

## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr
